export const foodData = [
	{
		id: "1",
		title: "ブルックリン アロハビール",
		subTitle: "",
		menu: "ロコモコ",
		description: "",
		image: "/assets/menu/1/1.jpg",
		imgClass: "",
	},
	{
		id: "2",
		title: "コロナビール ラニカイビール",
		subTitle: "",
		menu: "パイナップルピラフ",
		description: "",
		image: "/assets/menu/2/2.jpg",
		// imgClass: "object-contain",
	},
	{
		id: "3",
		title: "ブルーム―ン",
		subTitle: "",
		menu: "ローストビーフ",
		description: "",
		image: "",
	},
	{
		id: "4",
		title: "コナビール",
		subTitle: "",
		menu: "ガーリックシュリンプ（ソフトシェルシュリンプ）",
		description: "",
		image: "/assets/menu/4/2.jpg",
	},
	{
		id: "5",
		title: "バドワイザー",
		subTitle: "",
		menu: "ハワイアンステーキ",
		description: "",
		image: "/assets/menu/5/1.jpg",
	},
	{
		id: "6",
		title: "ハワイアンカクテル",
		subTitle: "",
		menu: "マラサダ",
		description: "",
		image: "",
	},
];

export const drinkData = [
	{
		id: "41",
		shopNo: "1",
		title: "ブルックリン アロハビール",
		subTitle: "",
		menu: "ブルックリンビール生",
		description: "",
		image: "",
		imgClass: "",
	},
	{
		id: "42",
		shopNo: "2",
		title: "コロナビール ラニカイビール",
		subTitle: "",
		menu: "コロナビール",
		description: "",
		image: "",
		// imgClass: "object-contain",
	},
	{
		id: "43",
		shopNo: "3",
		title: "ブルーム―ン",
		menu: "ブルーム―ンビール生",
		description: "",
		image: "",
	},
	{
		id: "44",
		shopNo: "4",
		title: "コナビール",
		menu: "ビックウエーブゴールデンエール 樽",
		description: "",
		image: "",
	},
	{
		id: "45",
		shopNo: "5",
		title: "バドワイザー",
		menu: "バドワイザー",
		description: "",
		image: "",
	},
	{
		id: "46",
		shopNo: "6",
		title: "ハワイアンカクテル",
		menu: "パイナップルカクテル",
		description: "",
		image: "",
	},
];

export const shopInfo = [
	{
		id: "1",
		info: [
			{
				title: "ロコモコ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/1.jpg",
			},
			{
				title: "ハワイアンバーガー",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/2.jpg",
			},
			{
				title: "マヒマヒバーガー",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "エッグベネディクト",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "スパムむすび",
				price: "600",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/3.jpg",
			},
		],
	},
	{
		id: "2",
		info: [
			{
				title: "パイナップルピラフ",
				price: "1300",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/2.jpg",
			},
			{
				title: "ポギサーモン",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/1.jpg",
			},
			{
				title: "ポキツナ（マグロ）",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/3.jpg",
			},
			{
				title: "スマイルポテト",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/4.jpg",
			},
			{
				title: "モチコチキン",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/5.jpg",
			},
		],
	},
	{
		id: "3",
		info: [
			{
				title: "ローストビーフ",
				price: "1500",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ココナッツグリンカレー",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハワイアンフライドポテト",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/1.jpg",
			},
			{
				title: "アサイボール",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "4",
		info: [
			{
				title: "ガーリックシュリンプ（ソフトシェルシュリンプ）",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/2.jpg",
			},
			{
				title: "サイミン",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/1.jpg",
			},
			{
				title: "ポップコーンシュリンプ",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハワイアンスペアリブ",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/3.jpg",
			},
			{
				title: "フリフリチキン",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/4.jpg",
			},
		],
	},
	{
		id: "5",
		info: [
			{
				title: "ハワイアンステーキ",
				price: "1600",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/1.jpg",
			},
			{
				title: "ビックウエーブポテト",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/2.jpg",
			},
			{
				title: "ロブスターサンド",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "マヒマヒ＆チップ",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "オニオンリング",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "6",
		info: [
			{
				title: "マラサダ",
				price: "500",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "タロイモマラサダ",
				price: "500",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "シェーブアイス",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/1.jpg",
			},
			{
				title: "レインボーアイス",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/2.jpg",
			},
		],
	},
	{
		id: "41",
		info: [
			{
				title: "ブルックリンビール生",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "アロハブロンド",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ポップレイIPA",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハイカーズドリームIPA",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "42",
		info: [
			{
				title: "コロナビール",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ラニカイビール",
				price: "1800",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "43",
		info: [
			{
				title: "ブルーム―ンビール生",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ビアカクテル",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "スムージー",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "44",
		info: [
			{
				title: "ビックウエーブゴールデンエール 樽",
				price: "1100",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ビックウエーブゴールデンエール",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ロングボード",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハナレイアイランド",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "コナライトブロンドエール",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "45",
		info: [
			{
				title: "バドワイザー",
				price: "900",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "バドワイザーゼロ（ノンアルコール）",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	{
		id: "46",
		info: [
			{
				title: "パイナップルカクテル",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ブルーハワイ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "マイタイ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ピニャコラーダ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "モヒート",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハワイアンサンセット",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ハワイアンクリームソーダ",
				price: "800",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "パイナップルスカッシュ",
				price: "600",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "パッションフルーツスカッシュ",
				price: "600",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ストロベリースカッシュ",
				price: "600",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
];
