export const foodData = [
	{
		id: "1",
		title: "ブルックリン アロハビール",
		subTitle: "",
		food: "ロコモコ",
		drink: "ブルックリンビール生",
		description: "",
		drinkDescription: "",
		image: "/assets/menu/1/5.jpg",
		drinkImage: "/assets/menu/1/9.jpg",
		imgClass: "",
		shopImage: "/assets/shop/1.png",
	},
	{
		id: "2",
		title: "コロナビール ラニカイビール",
		subTitle: "",
		food: "パイナップルピラフ",
		drink: "コロナビール",
		description: "",
		drinkDescription: "",
		image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_4.jpg",
		drinkImage: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_7.jpg",
		shopImage: "/assets/shop/2.png",
		// imgClass: "object-contain",
	},
	{
		id: "3",
		title: "ブルーム―ン",
		subTitle: "",
		food: "ハワイアンフライドポテト",
		drink: "ブルーム―ンビール生",
		description: "",
		drinkDescription: "",
		image: "/assets/menu/3/3.jpg",
		drinkImage: "/assets/menu/3/9.jpg",
		shopImage: "/assets/shop/3.png",
	},
	{
		id: "4",
		title: "コナビール",
		subTitle: "",
		food: "ガーリックシュリンプ（ソフトシェルシュリンプ）",
		drink: "ビックウエーブゴールデンエール 樽",
		description: "",
		drinkDescription: "",
		image: "/assets/menu/4/5.jpg",
		drinkImage: "/assets/menu/4/10.jpg",
		shopImage: "/assets/shop/4.png",
	},
	{
		id: "5",
		title: "バドワイザー",
		subTitle: "",
		food: "ハワイアンステーキ",
		drink: "バドワイザー",
		description: "",
		drinkDescription: "",
		image: "/assets/menu/5/6.jpg",
		drinkImage: "/assets/menu/5/8.jpg",
		shopImage: "/assets/shop/5.png",
	},
	{
		id: "6",
		title: "ハワイアンカクテル",
		subTitle: "",
		food: "シェーブアイス",
		drink: "レインボーアイス",
		description: "",
		drinkDescription: "",
		image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_1.jpg",
		drinkImage: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_0.jpg",
		shopImage: "/assets/shop/6.png",
	},
];

// export const drinkData = [
// 	{
// 		id: "41",
// 		shopNo: "1",
// 		title: "ブルックリン アロハビール",
// 		subTitle: "",
// 		menu: "ブルックリンビール生",
// 		description: "",
// 		image: "",
// 		imgClass: "",
// 		shopImage: "/assets/shop/1.png",
// 	},
// 	{
// 		id: "42",
// 		shopNo: "2",
// 		title: "コロナビール ラニカイビール",
// 		subTitle: "",
// 		menu: "コロナビール",
// 		description: "",
// 		image: "",
// 		shopImage: "/assets/shop/2.png",
// 		// imgClass: "object-contain",
// 	},
// 	{
// 		id: "43",
// 		shopNo: "3",
// 		title: "ブルーム―ン",
// 		menu: "ブルーム―ンビール生",
// 		description: "",
// 		image: "",
// 		shopImage: "/assets/shop/3.png",
// 	},
// 	{
// 		id: "44",
// 		shopNo: "4",
// 		title: "コナビール",
// 		menu: "ビックウエーブゴールデンエール 樽",
// 		description: "",
// 		image: "",
// 		shopImage: "/assets/shop/4.png",
// 	},
// 	{
// 		id: "45",
// 		shopNo: "5",
// 		title: "バドワイザー",
// 		menu: "バドワイザー",
// 		description: "",
// 		image: "",
// 		shopImage: "/assets/shop/5.png",
// 	},
// 	{
// 		id: "46",
// 		shopNo: "6",
// 		title: "ハワイアンカクテル",
// 		menu: "パイナップルカクテル",
// 		description: "",
// 		image: "",
// 		shopImage: "/assets/shop/6.png",
// 	},
// ];

export const shopInfo = [
	{
		id: "1",
		info: [
			{
				title: "ブルックリンビール生",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/9.jpg",
			},
			{
				title: "アロハブロンド",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/8.jpg",
			},
			{
				title: "ポップレイIPA",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/7.jpg",
			},
			{
				title: "ハイカーズドリームIPA",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/6.jpg",
			},
			{
				title: "ロコモコ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/5.jpg",
			},
			{
				title: "ハワイアンバーガー",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/4.jpg",
			},
			{
				title: "マヒマヒバーガー",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/3.jpg",
			},
			{
				title: "エッグベネディクト",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/2.jpg",
			},
			{
				title: "スパムむすび",
				price: "600",
				catchcopy: "",
				description: "",
				image: "/assets/menu/1/1.jpg",
			},
		],
	},
	{
		id: "2",
		info: [
			{
				title: "コロナビール",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_7.jpg",
			},
			{
				title: "ライカイ ピルボックスポーター",
				price: "1800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_5.jpg",
			},
			{
				title: "ラニカイ モクインペリアルIPA",
				price: "1800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_6.jpg",
			},
			{
				title: "パイナップルピラフ",
				price: "1300",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_4.jpg",
			},
			{
				title: "サーモンポギ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_3.jpg",
			},
			{
				title: "マグロポキ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_2.jpg",
			},
			{
				title: "スマイルポテト",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_1.jpg",
			},
			{
				title: "モチコチキン",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/2/LINE_ALBUM_02_コロナ_ラニカイ_240718_0.jpg",
			},
		],
	},
	{
		id: "3",
		info: [
			{
				title: "ブルーム―ンビール生",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/9.jpg",
			},
			{
				title: "ビアカクテル パイナップル",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/6.jpg",
			},
			{
				title: "ビアカクテル オレンジ",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/7.jpg",
			},
			{
				title: "ビアカクテル グリーンアップル",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/8.jpg",
			},
			{
				title: "ローストビーフ",
				price: "1500",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/5.jpg",
			},
			{
				title: "ココナッツグリンカレー",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/4.jpg",
			},
			{
				title: "ハワイアンフライドポテト",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/3.jpg",
			},
			{
				title: "アサイボール",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/2.jpg",
			},
			{
				title: "スムージー",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/3/1.jpg",
			},
		],
	},
	{
		id: "4",
		info: [
			{
				title: "ビックウエーブゴールデンエール 樽",
				price: "1100",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/10.jpg",
			},
			{
				title: "ビックウエーブゴールデンエール",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/9.jpg",
			},
			{
				title: "ロングボードラガー",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/8.jpg",
			},
			{
				title: "ハナレイアイランド",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/7.jpg",
			},
			{
				title: "コナライトブロンドエール",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/6.jpg",
			},
			{
				title: "ガーリックシュリンプ（ソフトシェルシュリンプ）",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/5.jpg",
			},
			{
				title: "サイミン",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/4.jpg",
			},
			{
				title: "ポップコーンシュリンプ",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/3.jpg",
			},
			{
				title: "ハワイアンスペアリブ",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/2.jpg",
			},
			{
				title: "フリフリチキン",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/4/1.jpg",
			},
		],
	},
	{
		id: "5",
		info: [
			{
				title: "バドワイザー",
				price: "900",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/8.jpg",
			},
			{
				title: "バドワイザーゼロ（ノンアルコール）",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/7.jpg",
			},
			{
				title: "バドワイザーレモンビール",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/9.jpg",
			},
			{
				title: "ハワイアンステーキ",
				price: "1600",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/6.jpg",
			},
			{
				title: "ハワイアンパンケーキ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/1.jpg",
			},
			{
				title: "ビックウエーブポテト",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/5.jpg",
			},
			{
				title: "ロブスターサンド",
				price: "1200",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/4.jpg",
			},
			{
				title: "マヒマヒ＆チップ",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/3.jpg",
			},
			{
				title: "オニオンリング",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/5/2.jpg",
			},
		],
	},
	{
		id: "6",
		info: [
			{
				title: "マラサダ",
				price: "500",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_2.jpg",
			},
			{
				title: "コナコーヒー（ホット・アイス）",
				price: "600",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_3.jpg",
			},
			{
				title: "タロイモマラサダ",
				price: "500",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "シェーブアイス",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_1.jpg",
			},
			{
				title: "レインボーアイス",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_0.jpg",
			},
			{
				title: "パイナップルカクテル",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_10.jpg",
			},
			{
				title: "ブルーハワイ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_9.jpg",
			},
			{
				title: "マイタイ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_8.jpg",
			},
			{
				title: "ピニャコラーダ",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_7.jpg",
			},
			{
				title: "モヒート",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_6.jpg",
			},
			{
				title: "ハワイアンサンセット",
				price: "1000",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_5.jpg",
			},
			{
				title: "ハワイアンクリームソーダ",
				price: "800",
				catchcopy: "",
				description: "",
				image: "/assets/menu/6/LINE_ALBUM_06_ハワイアンカクテル_240718_4.jpg",
			},
			{
				title: "パイナップルスカッシュ",
				price: "600",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "パッションフルーツスカッシュ",
				price: "600",
				catchcopy: "",
				description: "",
				image: "",
			},
			{
				title: "ストロベリースカッシュ",
				price: "600",
				catchcopy: "",
				description: "",
				image: "",
			},
		],
	},
	// {
	// 	id: "41",
	// 	info: [
	// 		{
	// 			title: "ブルックリンビール生",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "アロハブロンド",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ポップレイIPA",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ハイカーズドリームIPA",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 	],
	// },
	// {
	// 	id: "42",
	// 	info: [
	// 		{
	// 			title: "コロナビール",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ラニカイビール",
	// 			price: "1800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 	],
	// },
	// {
	// 	id: "43",
	// 	info: [
	// 		{
	// 			title: "ブルーム―ンビール生",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ビアカクテル",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "スムージー",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 	],
	// },
	// {
	// 	id: "44",
	// 	info: [
	// 		{
	// 			title: "ビックウエーブゴールデンエール 樽",
	// 			price: "1100",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ビックウエーブゴールデンエール",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ロングボード",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ハナレイアイランド",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "コナライトブロンドエール",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 	],
	// },
	// {
	// 	id: "45",
	// 	info: [
	// 		{
	// 			title: "バドワイザー",
	// 			price: "900",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "バドワイザーゼロ（ノンアルコール）",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 	],
	// },
	// {
	// 	id: "46",
	// 	info: [
	// 		{
	// 			title: "パイナップルカクテル",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ブルーハワイ",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "マイタイ",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ピニャコラーダ",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "モヒート",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ハワイアンサンセット",
	// 			price: "1000",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ハワイアンクリームソーダ",
	// 			price: "800",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "パイナップルスカッシュ",
	// 			price: "600",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "パッションフルーツスカッシュ",
	// 			price: "600",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 		{
	// 			title: "ストロベリースカッシュ",
	// 			price: "600",
	// 			catchcopy: "",
	// 			description: "",
	// 			image: "",
	// 		},
	// 	],
	// },
];
